# Generated by Django 3.0.1 on 2020-02-24 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(default='ground', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_type', models.CharField(default='econom', max_length=50)),
                ('price_multiplier', models.IntegerField(default=1, verbose_name='Enter here a price multiplier (X2, X3 for premium delivery e.g.')),
            ],
        ),
        migrations.CreateModel(
            name='Vehisle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(default='unknown', help_text='Enter here the model of vehisle', max_length=50)),
                ('kind_of_vehisle', models.CharField(help_text='Kind of vehisle(helicopter, truck, ship and other) ', max_length=70)),
                ('photo', models.ImageField(default='photo', upload_to='')),
                ('price_per_use', models.IntegerField(default=100)),
                ('price_per_km', models.IntegerField(default=20)),
                ('km_per_day', models.PositiveSmallIntegerField(default=50, help_text='How much transport does it cover kilometers per day')),
                ('maximum_load', models.IntegerField(default=1000, help_text='Enter maximum load in kilogramms')),
                ('cargo_volume', models.IntegerField(default=10, help_text='Enter cargo volume in cubic meter')),
                ('delivery_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.DeliveryMethod')),
            ],
        ),
    ]
