# Generated by Django 3.0.1 on 2020-02-24 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverytype',
            name='price_multiplier',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='vehisle',
            name='kind_of_vehisle',
            field=models.CharField(default='truck', help_text='Kind of vehisle(helicopter, truck, ship and others)', max_length=70),
        ),
    ]
