# Generated by Django 3.0.1 on 2020-02-24 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0003_auto_20200224_2224'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehisle',
            name='status',
            field=models.CharField(blank=True, choices=[('a', 'Available'), ('u', 'Unavailable'), ('m', 'Maintenance'), ('b', 'Booked')], default='m', max_length=1),
        ),
        migrations.AlterField(
            model_name='vehisle',
            name='delivery_method',
            field=models.CharField(blank=True, choices=[('ground', 'Ground'), ('air', 'Air'), ('sea', 'Sea')], default='g', max_length=6),
        ),
    ]
