# Generated by Django 3.0.1 on 2020-02-24 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0005_auto_20200224_2254'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehisle',
            name='status',
            field=models.CharField(blank=True, choices=[('a', 'Available'), ('u', 'Unavailable'), ('m', 'Maintenance'), ('b', 'Booked')], default='m', max_length=1),
        ),
    ]
