# Generated by Django 3.0.1 on 2020-02-24 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0006_vehisle_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DeliveryType',
            new_name='DeliveryClass',
        ),
        migrations.RenameField(
            model_name='deliveryclass',
            old_name='delivery_type',
            new_name='delivery_class',
        ),
    ]
