# Generated by Django 3.0.1 on 2020-03-03 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0007_auto_20200224_2311'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deliveryclass',
            options={'verbose_name': 'Delivery class', 'verbose_name_plural': 'Delivery classes'},
        ),
        migrations.AlterModelOptions(
            name='vehisle',
            options={'ordering': ['price_per_use', 'maximum_load', 'cargo_volume']},
        ),
    ]
