# Generated by Django 3.0.1 on 2020-03-11 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0009_news'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'News', 'verbose_name_plural': 'News'},
        ),
        migrations.AddField(
            model_name='news',
            name='title_image',
            field=models.ImageField(default='none', upload_to=''),
        ),
    ]
