# Generated by Django 3.0.1 on 2020-03-11 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0010_auto_20200311_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='short_description',
            field=models.CharField(default='Desctiption', max_length=200),
        ),
    ]
