# Generated by Django 3.0.1 on 2020-03-24 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0011_news_short_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuickQuote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
