# Generated by Django 3.0.1 on 2020-03-24 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0012_quickquote'),
    ]

    operations = [
        migrations.AddField(
            model_name='quickquote',
            name='email',
            field=models.EmailField(default='test@test.com', max_length=254),
        ),
        migrations.AddField(
            model_name='quickquote',
            name='message',
            field=models.CharField(default='None', max_length=200),
        ),
        migrations.AddField(
            model_name='quickquote',
            name='name',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AddField(
            model_name='quickquote',
            name='phone',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quickquote',
            name='service',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AddField(
            model_name='quickquote',
            name='subject',
            field=models.CharField(default='None', max_length=50),
        ),
    ]
