# Generated by Django 3.0.1 on 2020-03-24 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0013_auto_20200324_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quickquote',
            name='email',
            field=models.EmailField(default='Your@EmailAdress', max_length=254),
        ),
        migrations.AlterField(
            model_name='quickquote',
            name='message',
            field=models.CharField(default='Message', max_length=200),
        ),
        migrations.AlterField(
            model_name='quickquote',
            name='name',
            field=models.CharField(default='Your Name', max_length=50),
        ),
        migrations.AlterField(
            model_name='quickquote',
            name='service',
            field=models.CharField(default='Service', max_length=50),
        ),
        migrations.AlterField(
            model_name='quickquote',
            name='subject',
            field=models.CharField(default='Subject', max_length=50),
        ),
    ]
