# Generated by Django 3.0.1 on 2020-03-25 19:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0015_auto_20200325_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='pub_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 3, 25, 22, 8, 20, 464407)),
        ),
    ]
