# Generated by Django 3.0.1 on 2020-03-26 21:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0016_auto_20200325_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='pub_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 3, 27, 0, 34, 23, 177465)),
        ),
    ]
