# Generated by Django 3.0.1 on 2020-03-26 22:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0017_auto_20200327_0034'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='important_status',
            field=models.BooleanField(default=False, help_text='Are this news important or not'),
        ),
        migrations.AlterField(
            model_name='news',
            name='pub_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 3, 27, 1, 15, 59, 310318)),
        ),
    ]
