# Generated by Django 3.0.1 on 2020-03-31 20:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0018_auto_20200327_0115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='pub_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 3, 31, 23, 29, 35, 419149)),
        ),
    ]
