# Generated by Django 3.0.1 on 2020-04-11 21:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0019_auto_20200331_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='pub_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 12, 0, 49, 57, 250553)),
        ),
        migrations.AlterField(
            model_name='news',
            name='short_description',
            field=models.CharField(default='Description', max_length=200),
        ),
    ]
