# Generated by Django 3.0.1 on 2020-04-13 09:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0025_auto_20200413_1248'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newscomment',
            old_name='comments',
            new_name='news',
        ),
        migrations.AlterField(
            model_name='news',
            name='pub_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 13, 12, 49, 50, 967832)),
        ),
    ]
