# Generated by Django 3.0.1 on 2020-04-13 18:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0027_auto_20200413_2139'),
    ]

    operations = [
        migrations.AddField(
            model_name='newscomment',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 13, 21, 40, 9, 145420)),
        ),
        migrations.AlterField(
            model_name='news',
            name='pub_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 13, 21, 40, 9, 147420)),
        ),
    ]
