# Generated by Django 3.0.1 on 2020-04-13 18:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0028_auto_20200413_2140'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newscomment',
            options={'ordering': ['-pub_date']},
        ),
        migrations.AlterField(
            model_name='news',
            name='pub_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 13, 21, 41, 8, 279616)),
        ),
        migrations.AlterField(
            model_name='newscomment',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 13, 21, 41, 8, 278616)),
        ),
    ]
