# Generated by Django 3.0.1 on 2020-04-27 09:46

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0035_auto_20200418_2338'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-pub_date'], 'verbose_name': ' News', 'verbose_name_plural': 'News'},
        ),
        migrations.AlterModelOptions(
            name='proposednews',
            options={'ordering': ['-pub_date'], 'verbose_name': 'Proposed news', 'verbose_name_plural': 'Proposed news'},
        ),
        migrations.AddField(
            model_name='newscomment',
            name='answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='delivery.NewsComment'),
        ),
        migrations.AlterField(
            model_name='news',
            name='pub_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 27, 12, 46, 6, 921660)),
        ),
        migrations.AlterField(
            model_name='newscomment',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 27, 12, 46, 6, 920660), editable=False),
        ),
        migrations.AlterField(
            model_name='proposednews',
            name='pub_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 27, 12, 46, 6, 925660)),
        ),
    ]
