# Generated by Django 3.0.1 on 2020-04-27 12:19

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0036_auto_20200427_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='pub_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 27, 15, 19, 58, 709602)),
        ),
        migrations.AlterField(
            model_name='newscomment',
            name='answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_answer', to='delivery.NewsComment'),
        ),
        migrations.AlterField(
            model_name='newscomment',
            name='news',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='news_comment', to='delivery.News'),
        ),
        migrations.AlterField(
            model_name='newscomment',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 27, 15, 19, 58, 708603), editable=False),
        ),
        migrations.AlterField(
            model_name='proposednews',
            name='pub_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 27, 15, 19, 58, 710602)),
        ),
    ]
